### ISSUE TITLE
Support Lexicon in properties

### ISSUE THREAD

**Issue by MikeMichel** [BobRay/ActivationEmail#5]
Having a multi language site i want to have the emal subject in the right language. If i insert a lexicon entry in the properties the subject will have the name of the lexicon but not the content.

**Comment by BobRay** [comment]
I'm afraid I don't understand your issue.

**Comment by MikeMichel** [comment]
If i put [[%subject]] into the activeSubject field the subject in the emai is [[%subject]] instead of the translated value of the lexicon entry.

**Comment by BobRay** [comment]
Ah, try this -- edit the Plugin and on the "Properties" tab, scroll down and check "Pre-process tags in Property Values". 

It may not work as you want, though, because the snippet won't know what language you want. You can specify the language in the tag: [[%subject? &language=`es`]], but if you want multiple languages, I can't think of any way to accomplish it.

You're in the Manager context when you activate a user, so if your language feature is context-dependent, there's no way for a plugin to know which language you want unless you can use the cultureKey or manager_language System Settings, in which case you'd want to add something like this to the tag:  &language=`[[++cultureKey]]`

**Comment by MikeMichel** [comment]
right, tried ```[[%subject? &language=[[*context_key]]]]``` but no luck.

thx anyway

**Comment by BobRay** [comment]
I'm sorry it didn't work out.Did you put the context_key tag in back-ticks (they don't show up well here). I probably won't matter, but it's worth a try.

[[%subject? &language=\`[[*context_key]]\` ]]
